[smtp.mail1]
tls = true
host = "YOUR_SMTP_SERVER"
port = 587
username = "YOUR_SMTP_USERNAME"
password = "YOUR_SMTP_PASSWORD"

[smpp.sms1]
host = "YOUR_SMPP_SERVER"
port = 2775
username = "YOUR_SMPP_SYSTEM_ID"
password = "YOUR_SMPP_PASSWORD"

[telegram_bot.telegram1]
token = "YOUR_TELEGRAM_TOKEN"

[whatsapp_business.whatsapp1]
phone_id = 123_456_789_0  # Your Phone ID
token = "YOUR_WHATSAPP_TOKEN"

[slack.slack1]
token = "xoxb-YOUR_SLACK_BOT_TOKEN"
